"""changed password column name to password hash

Revision ID: 34635f508fcf
Revises: bed04f655d87
Create Date: 2022-09-15 11:28:54.882230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34635f508fcf'
down_revision = 'bed04f655d87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(length=102), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###
