"""empty message

Revision ID: a4918888203e
Revises: c26340962727
Create Date: 2022-10-01 21:57:53.680460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4918888203e'
down_revision = 'c26340962727'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('payload', sa.Text(), nullable=True))
    op.drop_column('notification', 'payload_json')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('payload_json', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('notification', 'payload')
    # ### end Alembic commands ###
