"""Added more tables

Revision ID: bed04f655d87
Revises: 03833c397648
Create Date: 2022-09-14 21:43:55.700029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bed04f655d87'
down_revision = '03833c397648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('denomination',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_denomination_price'), 'denomination', ['price'], unique=True)
    op.create_table('drawlocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drawlocation_location'), 'drawlocation', ['location'], unique=True)
    op.create_table('drawnumber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('bond',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('denomination_id', sa.Integer(), nullable=False),
    sa.Column('serial', sa.String(length=6), nullable=False),
    sa.ForeignKeyConstraint(['denomination_id'], ['denomination.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('denomination_id', 'serial', name='unique_bond')
    )
    op.create_table('drawdate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('denomination_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['denomination_id'], ['denomination.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'denomination_id', name='unique_drawdate')
    )
    op.create_index(op.f('ix_drawdate_date'), 'drawdate', ['date'], unique=False)
    op.create_table('prize',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('denomination_id', sa.Integer(), nullable=False),
    sa.Column('prize', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['denomination_id'], ['denomination.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('denomination_id', 'prize', name='unique_prize')
    )
    op.create_index(op.f('ix_prize_position'), 'prize', ['position'], unique=False)
    op.create_index(op.f('ix_prize_prize'), 'prize', ['prize'], unique=True)
    op.create_table('updatedlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_id', sa.Integer(), nullable=False),
    sa.Column('denomination_id', sa.Integer(), nullable=False),
    sa.Column('uploaded', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['date_id'], ['drawdate.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['denomination_id'], ['denomination.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date_id', 'denomination_id', name='unique_bond_list')
    )
    op.create_table('userbond',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bond_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bond_id'], ['bond.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'bond_id')
    )
    op.create_table('winningbond',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bond_id', sa.Integer(), nullable=False),
    sa.Column('prize_id', sa.Integer(), nullable=False),
    sa.Column('date_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('draw_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bond_id'], ['bond.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['date_id'], ['drawdate.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['draw_id'], ['drawnumber.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['location_id'], ['drawlocation.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['prize_id'], ['prize.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bond_id', 'prize_id', 'date_id', name='unique_winner')
    )
    op.add_column('role', sa.Column('name', sa.String(length=20), nullable=False))
    op.drop_index('ix_role_role_name', table_name='role')
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=True)
    op.drop_column('role', 'role_name')
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=102), autoincrement=False, nullable=False))
    op.add_column('role', sa.Column('role_name', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.create_index('ix_role_role_name', 'role', ['role_name'], unique=False)
    op.drop_column('role', 'name')
    op.drop_table('winningbond')
    op.drop_table('userbond')
    op.drop_table('updatedlists')
    op.drop_index(op.f('ix_prize_prize'), table_name='prize')
    op.drop_index(op.f('ix_prize_position'), table_name='prize')
    op.drop_table('prize')
    op.drop_index(op.f('ix_drawdate_date'), table_name='drawdate')
    op.drop_table('drawdate')
    op.drop_table('bond')
    op.drop_table('drawnumber')
    op.drop_index(op.f('ix_drawlocation_location'), table_name='drawlocation')
    op.drop_table('drawlocation')
    op.drop_index(op.f('ix_denomination_price'), table_name='denomination')
    op.drop_table('denomination')
    # ### end Alembic commands ###
